# 导入必要库

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from os import listdir

In [2]:
from keras.preprocessing import sequence 
from keras.models import Sequential 
from keras.layers import Dense 
from keras.layers import LSTM 

from keras.optimizers import adam_v2
from keras.models import load_model 
from keras.callbacks import ModelCheckpoint

# 预览数据

In [3]:
# 一期数据
df = pd.read_csv("10-15一期实验数据/10-15-001.csv", header=None, usecols=[0,1,2,3,4,5])
df.head()

0      1     2    3    4    5
0   9856 -13888 -2292 -904 -136 -170
1   9764 -13860 -2212 -602 -403  -35
2   9696 -14000 -2020 -644 -184   18
3  10020 -13732 -2276 -575 -418  -42
4   9844 -13880 -2096 -733 -397   24

In [4]:
# 二期数据
df = pd.read_csv("11.28实验2/back001.csv", header=None, usecols=[0,1,2,3,4,5])
df.head()

FileNotFoundError: [Errno 2] File b'11.28\xe5\xae\x9e\xe9\xaa\x8c2/back001.csv' does not exist: b'11.28\xe5\xae\x9e\xe9\xaa\x8c2/back001.csv'

# 处理数据长度

In [5]:
# 一期数据
path = "10-15一期实验数据/"
sequences = list()
# 正样本数据
for i in range(1, 39):
    if i < 10:
        filePath = path + "10-15-00" + str(i) + ".csv"
    else:
        filePath = path + "10-15-0" + str(i) + ".csv"
    print(filePath)
    df = pd.read_csv(filePath, header=None, usecols=[0,1,2,3,4,5]).dropna(axis=0,how='any')
    values = df.values
    sequences.append(values)
# 负样本数据
for i in range(1, 20):
    filePath = path + "0-" + str(i) + ".csv"
    print(filePath)
    df = pd.read_csv(filePath, header=None, usecols=[0,1,2,3,4,5]).dropna(axis=0,how='any')
    values = df.values
    sequences.append(values)

10-15一期实验数据/10-15-001.csv
10-15一期实验数据/10-15-002.csv
10-15一期实验数据/10-15-003.csv
10-15一期实验数据/10-15-004.csv
10-15一期实验数据/10-15-005.csv
10-15一期实验数据/10-15-006.csv
10-15一期实验数据/10-15-007.csv
10-15一期实验数据/10-15-008.csv
10-15一期实验数据/10-15-009.csv
10-15一期实验数据/10-15-010.csv
10-15一期实验数据/10-15-011.csv
10-15一期实验数据/10-15-012.csv
10-15一期实验数据/10-15-013.csv
10-15一期实验数据/10-15-014.csv
10-15一期实验数据/10-15-015.csv
10-15一期实验数据/10-15-016.csv
10-15一期实验数据/10-15-017.csv
10-15一期实验数据/10-15-018.csv
10-15一期实验数据/10-15-019.csv
10-15一期实验数据/10-15-020.csv
10-15一期实验数据/10-15-021.csv
10-15一期实验数据/10-15-022.csv
10-15一期实验数据/10-15-023.csv
10-15一期实验数据/10-15-024.csv
10-15一期实验数据/10-15-025.csv
10-15一期实验数据/10-15-026.csv
10-15一期实验数据/10-15-027.csv
10-15一期实验数据/10-15-028.csv
10-15一期实验数据/10-15-029.csv
10-15一期实验数据/10-15-030.csv
10-15一期实验数据/10-15-031.csv
10-15一期实验数据/10-15-032.csv
10-15一期实验数据/10-15-033.csv
10-15一期实验数据/10-15-034.csv
10-15一期实验数据/10-15-035.csv
10-15一期实验数据/10-15-036.csv
10-15一期实验数据/10-15-037.csv
10-15一期实验数据/10-15-038.csv
10-15一期实验数据/

In [6]:
# 二期数据

In [7]:
targets = pd.read_csv("10-15一期实验数据/target.csv", header=None).values

In [8]:
sequences[2]

array([['5640', -15560.0, -9056.0, 16162.0, 1681.0, -4854.0],
       ['15228', -15304.0, -4484.0, -8712.0, -3144.0, -2822.0],
       ['908', -10948.0, -3136.0, -1179.0, 21607.0, 1677.0],
       ['23396', -7320.0, 13200.0, -12837.0, -24070.0, 4660.0],
       ['4764', 13020.0, -21780.0, -11273.0, 2803.0, -19330.0],
       ['2480', -1220.0, -18508.0, -1977.0, -8074.0, -5586.0],
       ['396', -1760.0, -17168.0, -827.0, -1376.0, 929.0],
       ['16', -1296.0, -17632.0, -419.0, 841.0, -422.0],
       ['740', -1248.0, -17440.0, -455.0, -735.0, -55.0],
       ['588', -1416.0, -17392.0, -760.0, 28.0, -57.0],
       ['600', -1356.0, -17472.0, -646.0, -187.0, -10.0],
       ['712', -1348.0, -17384.0, -605.0, -358.0, 49.0],
       ['916', -1304.0, -17356.0, -573.0, -464.0, -72.0],
       ['836', -1324.0, -17396.0, -652.0, -373.0, 7.0],
       ['1616', -1228.0, -17608.0, -730.0, 1461.0, -224.0],
       ['2340', -1060.0, -17520.0, -562.0, -23.0, -249.0],
       ['2776', -1400.0, -17400.0, -752.0, -

In [9]:
targets

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

**由于时间序列数据长度不一，我们不能直接在这个数据集上建立模型。先找出最小、最大和平均长度：**

In [10]:
len_sequences = [] 
for one_seq in sequences: 
    len_sequences.append(len(one_seq)) 
pd.Series(len_sequences).describe()

count    57.000000
mean     29.526316
std       9.708438
min      13.000000
25%      26.000000
50%      29.000000
75%      33.000000
max      84.000000
dtype: float64

**大多数文件的长度在$20$到$40$之间。只有极少个文件的长度超过$60$。因此，取最小或最大长度没有多大意义。选择上四分位数作为序列的长度，进行数据处理**

In [11]:
#用最后一行的值填充序列到最大长度
to_pad = 84
new_seq = []
for one_seq in sequences:
    len_one_seq = len(one_seq)
    last_val = one_seq[-1]
    n = to_pad - len_one_seq
   
    to_concat = np.repeat(one_seq[-1], n).reshape(6, n).transpose()
    new_one_seq = np.concatenate([one_seq, to_concat])
    new_seq.append(new_one_seq)
final_seq = np.stack(new_seq)

#将序列截断为长度 33
from keras.preprocessing import sequence
seq_len = 33
final_seq=sequence.pad_sequences(final_seq, maxlen=seq_len, padding='post', dtype='float', truncating='post')

In [12]:
final_seq.shape

(57, 33, 6)

In [13]:
final_seq

array([[[ 9.8560e+03, -1.3888e+04, -2.2920e+03, -9.0400e+02,
         -1.3600e+02, -1.7000e+02],
        [ 9.7640e+03, -1.3860e+04, -2.2120e+03, -6.0200e+02,
         -4.0300e+02, -3.5000e+01],
        [ 9.6960e+03, -1.4000e+04, -2.0200e+03, -6.4400e+02,
         -1.8400e+02,  1.8000e+01],
        ...,
        [ 5.6640e+03, -6.6400e+02, -1.6752e+04, -7.5700e+02,
         -4.0900e+02,  7.0000e+01],
        [ 5.5640e+03, -6.9600e+02, -1.6752e+04, -7.8300e+02,
         -3.2300e+02,  1.3100e+02],
        [ 5.7560e+03, -5.6800e+02, -1.6908e+04, -7.6100e+02,
          1.1300e+02,  1.5900e+02]],

       [[ 5.0920e+03, -1.5816e+04, -3.7960e+03, -5.6600e+02,
         -6.8200e+02,  3.8000e+01],
        [ 4.7440e+03, -1.5988e+04, -3.0280e+03, -7.3700e+02,
         -7.0000e+00, -7.0000e+01],
        [ 5.3400e+03, -1.5760e+04, -3.1600e+03, -1.2190e+03,
          9.2900e+02, -1.0300e+02],
        ...,
        [-1.5288e+04, -2.7560e+03, -2.5560e+03, -6.5800e+02,
          1.8700e+02,  1.3000e+01],
  

# 构建训练集和测试集

In [27]:
# 引入训练集、测试集划分函数
from sklearn.model_selection import train_test_split

# 将数据集按照 80% 和 20% 的比例随机划分为训练集和测试集
train_data, test_data, train_target, test_target = train_test_split(final_seq, targets)
test_target.shape

(15, 1)

In [28]:
train_data = np.array(train_data)
test_data = np.array(test_data)

train_target = np.array(train_target)
#train_target = (train_target+1)/2

test_target = np.array(test_target)
#test_target = (test_target+1)/2

# 构建 LSTM

In [33]:
model = Sequential() 
model.add(LSTM(256, input_shape=(seq_len, 6))) 
model.add(Dense(1, activation='ReLU'))

In [34]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 256)               269312    
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 257       
Total params: 269,569
Trainable params: 269,569
Non-trainable params: 0
_________________________________________________________________


In [35]:
adam = adam_v2.Adam(lr=0.001)
chk = ModelCheckpoint('best_model.pkl', monitor='val_acc', save_best_only=True, mode='max', verbose=1)
model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
model.fit(train_data, train_target, epochs=200, batch_size=128, callbacks=[chk])

Epoch 1/200
1/1 [==============================] - 2s 2s/step - loss: 1.4563 - accuracy: 0.8095
Epoch 2/200
1/1 [==============================] - 0s 67ms/step - loss: 1.2172 - accuracy: 0.8571
Epoch 3/200
1/1 [==============================] - 0s 52ms/step - loss: 1.1865 - accuracy: 0.8571
Epoch 4/200
1/1 [==============================] - 0s 54ms/step - loss: 1.1678 - accuracy: 0.8810
Epoch 5/200
1/1 [==============================] - 0s 53ms/step - loss: 1.1526 - accuracy: 0.9048
Epoch 6/200
1/1 [==============================] - 0s 54ms/step - loss: 1.1339 - accuracy: 0.9286
Epoch 7/200
1/1 [==============================] - 0s 54ms/step - loss: 1.1265 - accuracy: 0.9286
Epoch 8/200
1/1 [==============================] - 0s 63ms/step - loss: 1.1215 - accuracy: 0.9286
Epoch 9/200
1/1 [==============================] - 0s 53ms/step - loss: 0.8102 - accuracy: 0.9286
Epoch 10/200
1/1 [==============================] - 0s 57ms/step - loss: 0.7852 - accuracy: 0.9286
Epoch 11/200
1/1 [===

1/1 [==============================] - 0s 57ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 48/200
1/1 [==============================] - 0s 54ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 49/200
1/1 [==============================] - 0s 53ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 50/200
1/1 [==============================] - 0s 56ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 51/200
1/1 [==============================] - 0s 54ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 52/200
1/1 [==============================] - 0s 53ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 53/200
1/1 [==============================] - 0s 54ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 54/200
1/1 [==============================] - 0s 57ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 55/200
1/1 [==============================] - 0s 51ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 56/200
1/1 [==============================] - 0s 51ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 57/200
1/1 [=====

1/1 [==============================] - 0s 52ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 94/200
1/1 [==============================] - 0s 53ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 95/200
1/1 [==============================] - 0s 53ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 96/200
1/1 [==============================] - 0s 54ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 97/200
1/1 [==============================] - 0s 51ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 98/200
1/1 [==============================] - 0s 55ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 99/200
1/1 [==============================] - 0s 50ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 100/200
1/1 [==============================] - 0s 51ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 101/200
1/1 [==============================] - 0s 52ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 102/200
1/1 [==============================] - 0s 53ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 103/200
1/1 [=

1/1 [==============================] - 0s 54ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 140/200
1/1 [==============================] - 0s 54ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 141/200
1/1 [==============================] - 0s 52ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 142/200
1/1 [==============================] - 0s 54ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 143/200
1/1 [==============================] - 0s 52ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 144/200
1/1 [==============================] - 0s 53ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 145/200
1/1 [==============================] - 0s 55ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 146/200
1/1 [==============================] - 0s 53ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 147/200
1/1 [==============================] - 0s 52ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 148/200
1/1 [==============================] - 0s 49ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 149/200


1/1 [==============================] - 0s 52ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 186/200
1/1 [==============================] - 0s 54ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 187/200
1/1 [==============================] - 0s 53ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 188/200
1/1 [==============================] - 0s 57ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 189/200
1/1 [==============================] - 0s 53ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 190/200
1/1 [==============================] - 0s 55ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 191/200
1/1 [==============================] - 0s 52ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 192/200
1/1 [==============================] - 0s 55ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 193/200
1/1 [==============================] - 0s 59ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 194/200
1/1 [==============================] - 0s 54ms/step - loss: 0.7303 - accuracy: 0.9524
Epoch 195/200


# 检测结果

In [36]:
#model = load_model('best_model.pkl')

from sklearn.metrics import accuracy_score
test_preds = model.predict_classes(test_data)
print(test_target)
accuracy_score(test_target, test_preds)

[[1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


0.9333333333333333

# 保存模型

In [37]:
model.save("LSTM.h5")

In [38]:
model = load_model("LSTM.h5")

In [39]:
# 二期数据做测试
path_2 = "11.28实验2/"
sequences = list()
# 正样本数据
for i in range(1, 8):
    filePath = path_2 + "back00" + str(i) + ".csv"
    df = pd.read_csv(filePath, header=None, usecols=[0,1,2,3,4,5]).dropna(axis=0,how='any')
    print(filePath)
    values = df.values
    sequences.append(values)
for i in range(1, 41):
    if i < 10:
        filePath = path_2 + "left00" + str(i) + ".csv"
    else:
        filePath = path_2 + "left0" + str(i) + ".csv"
    print(filePath)
    df = pd.read_csv(filePath, header=None, usecols=[0,1,2,3,4,5]).dropna(axis=0,how='any')
    values = df.values
    sequences.append(values)
    
# 负样本数据
for i in range(1, 4):
    filePath = path_2 + "jump00" + str(i) + ".csv"
    print(filePath)
    df = pd.read_csv(filePath, header=None, usecols=[0,1,2,3,4,5]).dropna(axis=0,how='any')
    values = df.values
    sequences.append(values)
    
targets = pd.read_csv("11.28实验2/target.csv", header=None).values

len_sequences = [] 
for one_seq in sequences: 
    len_sequences.append(len(one_seq)) 

#用最后一行的值填充序列到最大长度
to_pad = 84
new_seq = []
for one_seq in sequences:
    len_one_seq = len(one_seq)
    last_val = one_seq[-1]
    n = to_pad - len_one_seq
   
    to_concat = np.repeat(one_seq[-1], n).reshape(6, n).transpose()
    new_one_seq = np.concatenate([one_seq, to_concat])
    new_seq.append(new_one_seq)
final_seq = np.stack(new_seq)

#将序列截断为长度 32
from keras.preprocessing import sequence
seq_len = 32
final_seq=sequence.pad_sequences(final_seq, maxlen=seq_len, padding='post', dtype='float', truncating='post')

test_data = final_seq
test_target = targets

11.28实验2/back001.csv
11.28实验2/back002.csv
11.28实验2/back003.csv
11.28实验2/back004.csv
11.28实验2/back005.csv
11.28实验2/back006.csv
11.28实验2/back007.csv
11.28实验2/left001.csv
11.28实验2/left002.csv
11.28实验2/left003.csv
11.28实验2/left004.csv
11.28实验2/left005.csv
11.28实验2/left006.csv
11.28实验2/left007.csv
11.28实验2/left008.csv
11.28实验2/left009.csv
11.28实验2/left010.csv
11.28实验2/left011.csv
11.28实验2/left012.csv
11.28实验2/left013.csv
11.28实验2/left014.csv
11.28实验2/left015.csv
11.28实验2/left016.csv
11.28实验2/left017.csv
11.28实验2/left018.csv
11.28实验2/left019.csv
11.28实验2/left020.csv
11.28实验2/left021.csv
11.28实验2/left022.csv
11.28实验2/left023.csv
11.28实验2/left024.csv
11.28实验2/left025.csv
11.28实验2/left026.csv
11.28实验2/left027.csv
11.28实验2/left028.csv
11.28实验2/left029.csv
11.28实验2/left030.csv
11.28实验2/left031.csv
11.28实验2/left032.csv
11.28实验2/left033.csv
11.28实验2/left034.csv
11.28实验2/left035.csv
11.28实验2/left036.csv
11.28实验2/left037.csv
11.28实验2/left038.csv
11.28实验2/left039.csv
11.28实验2/left040.csv
11.28实验2/jump

In [40]:
test_preds = model.predict_classes(test_data)
print(test_target)
accuracy_score(test_target, test_preds)

D:\Python-Anaconda3-64bit\lib\site-packages\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]]


0.84